### ISSUE TITLE
datumEither.fromOption has unknown type on left

### ISSUE THREAD

**Issue by ljani** [nullpub/datum#11]
I'm wondering why [`datumEither.fromOption` has `unknown` in its signature](https://github.com/nullpub/datum/blob/184a8ed8e49043de069e004fb19b44d70fe87c3d/src/DatumEither.ts#L239)? Shouldn't it be `E`?

For example, [`TaskEither` has `E` as well](https://github.com/gcanti/fp-ts/blob/9759cb09d7cead603925748adb5fae5c6919b728/src/TaskEither.ts#L117) and it is defined similarly as `Task<Either<E, A>>` vs `Datum<Either<E, A>>`.

Thanks for the wonderful project, it has been a pleasure to work with remote data!

**Comment by baetheus** [comment]
Looks like an oversight. I'll put together a patch this evening.
