### ISSUE TITLE
Support Additional Datum Monoid

### ISSUE THREAD

**Issue by SamProtas** [nullpub/datum#16]
I ran into a use case where I was combining two identically typed Datums. The semigroup behavior I wanted was:

- If either datum has a value, result has a value (concat-ing the underlying values if both present)
- If either datum isRefresh or isPending, the result isRefresh or isPending (based on whether the result has a value)

The monoid empty value that follows from this is `initial` (it has neither a value, or an indication of data being loaded, so with the above rules cannot affect another value its concat-ed with).

For a bit more context, I was loading a Map with two separate API calls and rendering the merged result. I wanted to show as much data as we've loaded so far, and I wanted to indicate if any additional loading was in progress, regardless of whether I've already loaded some data (refresh indicator).

I'm not sure what to call this monoid instance given there already exists one with different behavior in this library. `getProgressBiasedMonoid`? Open to naming suggestions and happy to submit a PR if you'd accept it.

**Comment by baetheus** [comment]
Hmm, this looks like incorrect logic in the `getSemigroup` function. I had assumed that this was the behavior that was implemented.
