### ISSUE TITLE
datumEither.chainW support?

### ISSUE THREAD

**Issue by ljani** [nullpub/datum#18]
I found myself in need of [`chainW`](https://gcanti.github.io/fp-ts/modules/Either.ts.html#chainw) with `datumEither.DatumEither<E1, Organization>` when I was trying to find a specific user and trying to return `NotFoundError`, ie. `datumEither.DatumEither<E1 | NotFound, User>`. Could it be supported?

I was trying to see how [`chain` was implemented](https://github.com/nullpub/datum/blob/0ee8a3d453d7bdf67a3197a920c53d0d9dd57731/src/DatumEither.ts#L470). It seems it is using [the deprecated `pipeable` module](https://gcanti.github.io/fp-ts/modules/pipeable.ts.html#pipeable), so some refactoring is probably needed.

**Comment by baetheus** [comment]
I don't really like the naming of chainW (or sequenceT, monadM, etc). In a different library I solved this by creating an identity function called widen: `const widen: <F>() => <E, A>(ta: DatumEither<E, A>) => DatumEither<E | F, A> = constant(identity)`. It's generally used like so:

```ts
const result = pipe(
  replete<number>(1),
  chain(n => pipe(
    replete<string>(n + 1),
    widen<string>(),
  ))
); // DatumEither<number | string, number>
```

It's clear that I need to do some spring cleaning in datum. I'll make a project and add this to the list.

As for pipeable deprecation and refactoring, almost all of the typeclass functions in datum are implemented [as curried functions](https://github.com/nullpub/datum/blob/0ee8a3d453d7bdf67a3197a920c53d0d9dd57731/src/Datum.ts#L370). So refactoring is likely just renaming and exporting these functions and removing the mega-adt object.

**Comment by ljani** [comment]
> In a different library I solved this by creating an identity function called widen: `const widen: <F>() => <E, A>(ta: DatumEither<E, A>) => DatumEither<E | F, A> = constant(identity)`

This is a great idea, thanks! I don't see any need for `chainW` anymore.
