### ISSUE TITLE
Proposal: Re-export modules from index file

### ISSUE THREAD

**Issue by alex-ketch** [nullpub/datum#4]
Hey @baetheus, thanks for this library!

As I was using it I came across a few ergonomic and method conflict issues, so was wondering if you'd be open to the following changes:

1. Create an `index` file to re-export the `Datum` and `DatumEither` methods from, pretty much identical to the [`fp-ts/index.ts` file](https://github.com/gcanti/fp-ts/blob/master/src/index.ts).
2. Add a `"main": "index.js"` field to `package.json`

This will allow easier namespaces imports, importing of both modules from the same path, and better discoverability as the package name can be used to import from.

E.g.

```ts
// new namespace
import { datum } from '@nll/datum'
datum.fold(…

// namespace alias
import { datum as D, datumEither as DE } from '@nll/datum'
D.fold(…
DE.fold(…

// usage as before still works
import { fold } from '@nll/datum/Datum'
fold(…
```

Can send a PR with the above changes if you'd like

**Comment by baetheus** [comment]
Hey, thanks! I would accept a PR for this.
